version: 0.1

phases:
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/codedeploye-test
      - mv scripts ./dist/codedeploye-test
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/codedeploye-test